# lsi: false
# safe: true
# source: https://github.com/ainimarie/ainimarie.github.io
# incremental: false
# highlighter: rouge
# gist:
#   noscript: false
collections:
  pages:
    output: true
    permalink: /:path/
    
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge