author:
  name: Aini
  github: ainimarie
  linkedin: aini.hyvarinen
# lsi: false
# safe: true
# source: https://github.com/ainimarie/ainimarie.github.io
# incremental: false
# gist:
#   noscript: false
collections:
  pages:
    output: true
    permalink: /:path/
  portfolio:
    output: true
    permalink: /:collection/:name
kramdown:
  math_engine: mathjax